version: '3.7'
networks:
  petstore:
    name: petstore
    driver: bridge

services:
  petstore:
    image: flask_petstore
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - petstore
    volumes:
      - .:/app
    container_name: petstore_api
    depends_on:
      - "petstore_mongo"
    env_file: env/prod.env

  petstore_mongo:
    image: mongo:3.0.2
    container_name: petstore_mongo
    hostname: "petstore_mongo"
    ports:
      - 27017:27017
    networks:
      - petstore
    restart: unless-stopped
